GET http://localhost:3000/api/courses

###
GET http://localhost:3000/api/courses/id/1


###
POST http://localhost:3000/api/courses/insert
Content-Type: application/json

{
    "title": "Introdução ao node",
    "price": 789.30
}